antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'cloud-release'
site:
  title: Spring Cloud Release
  url: https://docs.spring.io/spring-cloud-release/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
    - url: https://github.com/spring-cloud/spring-cloud-release
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main, 2025.0.x, 2024.0.x ]
      # 20[3-9][0-9].[0-9].[0-9]
      # 202[3-9].[0-9].[0-9] without 2023.0.0-M1
      tags: [ 'v20{2..9}+({0..9}).+({0..9}).+({0..9})?(-{RC,M}*)', '!v2023.0.0-M1', '!v2022.0.*', '!v2020.0.*', '!v2021.0.*' ]
      start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-cloud
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.18/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    format: pretty
