= Spring Cloud Train Reference Documentation

:spring-boot-version: 3.2.12

Spring Cloud provides tools for developers to quickly build some of
the common patterns in distributed systems (e.g. configuration
management, service discovery, circuit breakers, intelligent routing,
micro-proxy, control bus). Coordination of
distributed systems leads to boiler plate patterns, and using Spring
Cloud developers can quickly stand up services and applications that
implement those patterns. They will work well in any distributed
environment, including the developer's own laptop, bare metal data
centres, and managed platforms such as Cloud Foundry.

Release Train Version: *{spring-cloud-version}*

Supported Boot Version: *{spring-boot-version}*

== Features

Spring Cloud focuses on providing good out of box experience for typical use cases
and extensibility mechanism to cover others.

* Distributed/versioned configuration
* Service registration and discovery
* Routing
* Service-to-service calls
* Load balancing
* Circuit Breakers
* Distributed messaging

== Release Train Projects

Below we present links to the reference documentation of all the projects that contribute to this reference train.

[horizontal]
include::_spring-cloud-links.adoc[]
