name: Spring Cloud Release (Test)
on:
  workflow_dispatch:
    inputs:
      your-name:
        description: 'Your name'     
        required: true
        default: Unknown   
jobs:
  #BUILD
  spring-cloud-build:
     uses: spring-cloud/spring-cloud-build/.github/workflows/ci.yaml@main
     with:
        branches: main
     secrets:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        COMMERCIAL_ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
        COMMERCIAL_ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
